# SITE SETUP
title: Your Name | Embedded Systems Projects
description: A portfolio of electronics and IoT projects.
url: "https://devdrshn.github.io" # Replace with your URL

# JEKYLL THEME SETUP
theme: jekyll-theme-cayman # Or jekyll-theme-minimal, jekyll-theme-slate

# NAVIGATION
header_pages:
  - index.md
  - projects.md 
